
version: '3.7'
services:
  server:
    image: rancher/k3s:v1.0.0
    entrypoint: sh
    command: -c "mkdir -p /var/lib/rancher/k3s/agent/images; cp /images/* /var/lib/rancher/k3s/agent/images/; exec k3s server --disable-agent --https-listen-port 6443"
    tmpfs:
    - /var/lib/rancher/k3s/agent
    environment:
    - K3S_CLUSTER_SECRET=somethingtotallyrandom
    - K3S_KUBECONFIG_OUTPUT=/output/kubeconfig.yaml
    - K3S_KUBECONFIG_MODE=666
    volumes:
    - ./.images:/images
    ports:
    - 6443:6443

  node:
    image: rancher/k3s:v1.0.0
    entrypoint: sh
    command: -c "mkdir -p /var/lib/rancher/k3s/agent/images; cp /images/* /var/lib/rancher/k3s/agent/images/; exec k3s agent"
    tmpfs:
    - /run
    - /var/run
    privileged: true
    depends_on:
    - server
    volumes:
    - ./.images:/images
    - type: bind
      source: /dev/mapper
      target: /dev/mapper
      read_only: true
    environment:
    - K3S_URL=https://server:6443
    - K3S_CLUSTER_SECRET=somethingtotallyrandom